apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamforge-frontend
  labels:
    app: streamforge-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamforge-frontend
  template:
    metadata:
      labels:
        app: streamforge-frontend
    spec:
      containers:
      - name: streamforge-frontend
        image: 307946636040.dkr.ecr.sa-east-1.amazonaws.com/streamforge-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: ecr-secret
