apiVersion: v1
kind: Service
metadata:
  name: streamforge-frontend
  labels:
    app: streamforge-frontend
spec:
  selector:
    app: streamforge-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
